# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod "RxSwift"
  pod "RxCocoa"
  pod "Firebase/Core"
  pod "Firebase/Auth"

  pod 'lottie-ios'
  pod 'Alamofire'
  # Pods for MusicApp

  # pod 'Alamofie'

  target 'MusicAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicAppUITests' do
    # Pods for testing
  end

end
