# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'animalswiki' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for animalswiki
  pod "RxSwift"
  pod "RxCocoa"
  pod "Firebase/Core"
  pod "Firebase/Auth"
  pod 'lottie-ios'
  pod 'Lightbox'

  target 'animalswikiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'animalswikiUITests' do
    # Pods for testing
  end

end
