# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'belajar1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for belajar1
  pod "RxSwift"
  pod "RxCocoa"
  pod "Firebase/Core"
  pod "Firebase/Auth"
  pod 'lottie-ios'

  target 'belajar1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'belajar1UITests' do
    # Pods for testing
  end

end
